Melodic devel maarika
robotont/robotont_nuc_description pull request #2
Opened 2020-10-01 09:32 UTC by mmaao

2020-10-01 10:05 UTC, kruusamae commented
ahaa, väga põnev lahendus. @mmaao kas ma saan õigesti aru, et sa leidsid mooduse, kuidas anda realsense'ile vajalikud argumendid juba xacro-tasemel, seega ei pea nendega launch-faili tasemel tegelema?

2020-10-01 10:22 UTC, kruusamae requested changes

2020-10-01 10:22 UTC, kruusamae commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
kas päriselt on ka neid kahte rida tarvis? sest sa tegelikult ei kasuta neid argumente ju kusagil hiljem?
kui ma vaatasin d435 kirjeldust, siis seal on needsamad vaikeväärtused juba sees (vt https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_description/urdf/_d435.urdf.xacro)
ühesõnaga, ma pakuks, et kui sa need kaks rida ära kustutaks, siis ikka kõik toimiks. saad sa palun proovida?

2020-10-01 10:22 UTC, kruusamae commented on urdf/robotont_realsense.urdf.xacro
>  	<xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
siin on taane pisut erinev järgnevatest ridadest, aga vist ei peaks olema ;)

2020-10-01 10:33 UTC, mmaao commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
Ilma viskab seda vana head errorit, jah

2020-10-01 10:43 UTC, kruusamae commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
aga mis juhtub, kui sa `default="False"` asemel kirjutad `value="False"`?

2020-10-01 10:47 UTC, mmaao commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
Siis on: xacro:arg: missing attribute 'default'

Selle use_nominal_extrinsicsi saab sensros_d435 juurde alla panna tegelikult, aga add_plug'i puhul ma paremat varianti ei leidnud praegu.

2020-10-01 11:00 UTC, kruusamae commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
krt. ma olen hetkel segaduses. mulle tundub, et kogu selles xacro-majanduses on mingi puuk sees. see d435 include'imine ei tohiks nii keeruline olla. ja ma hetkel kaldun arvama, et meie xacros on mingid asjad üledefineeritud ja see lõhub asja ära. 2 rida peaks olema piisav, et d435 laadida. üks include faili jaoks ja teine macro laadimiseks. proovi kõik ülejäänud ära jätta ja vaata mis juhtub.

2020-10-01 11:33 UTC, mmaao commented on urdf/robotont_realsense.urdf.xacro
> +    <xacro:arg name= "add_plug" default="False" />
Nende enda näitefailis on nii:

```xml
<?xml version="1.0"?>
<robot name="realsense2_camera" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:arg name="use_nominal_extrinsics" default="false"/>
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
  
  <link name="base_link" />
  <xacro:sensor_d435 parent="base_link" use_nominal_extrinsics="$(arg use_nominal_extrinsics)">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d435>
</robot>
```
Aga neil on add_plug launch failis olemas jällegi.

2020-10-01 17:36 UTC, Veix123 approved these changes
See argumendi saatmine on kahtlane jah, vb midagi, mis uuemates ROS versioonides on lapitud. Testisin ja mõlemad launch failid minu masinas toimivad.

2020-10-06 21:51 UTC, Veix123 commented
Vähemalt mingis configuratsioonis tundub see argumentide vaikeväärtuste kasutamine ja ülekirjutamine toimivat: https://www.gitmemory.com/issue/ros/xacro/209/493654957

2020-10-08 08:19 UTC, kruusamae approved these changes

2020-10-08 08:20 UTC, merged